### ISSUE TITLE
点Test-Plugin的时候提示"No errors returned"

### ISSUE THREAD

**Issue by nicolas-tesla-x** [FeSeason/sentry-10-dingding#1]
点Test-Plugin的时候提示"No errors returned"
如果出现这个问题，是钉钉机器人的安全设置问题
需要勾选安全设置中的 “自定义关键词”，将关键词设置为 “项目异常” 即可

**Comment by FeSeason** [comment]
@renzhao1113 我是自定义关键字设置了 '/'
